--liquibase formatted sql
--changeset houndjo:00010-organization-create-table
CREATE TABLE IF NOT EXISTS organization (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name                  VARCHAR(150) NOT NULL,
    slug                  VARCHAR(160) NOT NULL,
    contact_email         VARCHAR(255) NOT NULL,
    phone_number          VARCHAR(20),
    address               VARCHAR(255),
    default_currency_code VARCHAR(10)  NOT NULL DEFAULT 'GNF',
    default_language_key  VARCHAR(5)   NOT NULL DEFAULT 'fr',
    timezone              VARCHAR(64)  NOT NULL DEFAULT 'Africa/Conakry',
    status                VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    creation_date         TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date      TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by       VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_organization PRIMARY KEY (id),
    CONSTRAINT uq_organization_slug UNIQUE (slug)
);
