--liquibase formatted sql
--changeset houndjo:00015-course-create-table
CREATE TABLE IF NOT EXISTS course (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id       BIGINT       NOT NULL,
    class_id              BIGINT       NOT NULL,
    name                  VARCHAR(150) NOT NULL,
    type                  VARCHAR(20)  NOT NULL,
    description           TEXT,
    quran_mode            VARCHAR(10),
    quran_scope_from_juz  SMALLINT,
    quran_scope_to_juz    SMALLINT,
    book_title            VARCHAR(150),
    book_total_chapters   SMALLINT,
    book_total_pages      SMALLINT,
    creation_date         TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date      TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by       VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_course PRIMARY KEY (id),
    CONSTRAINT fk_course_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_class FOREIGN KEY (class_id) REFERENCES school_class (id) ON DELETE CASCADE
);

CREATE INDEX idx_course_org ON course (organization_id);
CREATE INDEX idx_course_class ON course (class_id);
