--liquibase formatted sql
--changeset houndjo:00017-student-create-table
CREATE TABLE IF NOT EXISTS student (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id   BIGINT       NOT NULL,
    user_id           BIGINT       NULL,
    first_name        VARCHAR(255) NOT NULL,
    last_name         VARCHAR(255) NOT NULL,
    birth_date        DATE,
    gender            VARCHAR(6),
    guardian_name     VARCHAR(255),
    guardian_phone    VARCHAR(20),
    creation_date     TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date  TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_student PRIMARY KEY (id),
    CONSTRAINT fk_student_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE,
    CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL
);

CREATE INDEX idx_student_org ON student (organization_id);
CREATE INDEX idx_student_user ON student (user_id);
