--liquibase formatted sql
--changeset houndjo:00012-organization-invitation-create-table
CREATE TABLE IF NOT EXISTS organization_invitation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    organization_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    invitation_code TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(15) NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT now(),
    last_update_date TIMESTAMP NOT NULL DEFAULT now(),
    last_updated_by VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_organization_invitation PRIMARY KEY (id),
    CONSTRAINT fk_org_invitation_org FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT uq_org_invitation_code UNIQUE (invitation_code)
);
CREATE INDEX idx_org_invitation_org ON organization_invitation (organization_id);
