--liquibase formatted sql
--changeset houndjo:00011-membership-create-table
CREATE TABLE IF NOT EXISTS membership (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT       NOT NULL,
    organization_id  BIGINT       NOT NULL,
    role             VARCHAR(30)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    creation_date    TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by  VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_membership PRIMARY KEY (id),
    CONSTRAINT uq_membership_user_org UNIQUE (user_id, organization_id),
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE
);

CREATE INDEX idx_membership_org ON membership (organization_id);
CREATE INDEX idx_membership_user ON membership (user_id);
