--liquibase formatted sql
--changeset houndjo:00013-quran-reference-create-table
CREATE TABLE IF NOT EXISTS quran_surah (
    number            SMALLINT     NOT NULL,   -- 1..114
    name_arabic       VARCHAR(80)  NOT NULL,
    name_transliteration VARCHAR(80) NOT NULL,
    name_fr           VARCHAR(80)  NOT NULL,
    name_en           VARCHAR(80)  NOT NULL,
    revelation_place  VARCHAR(10)  NOT NULL,   -- MECCAN / MEDINAN
    verse_count       SMALLINT     NOT NULL,
    CONSTRAINT pk_quran_surah PRIMARY KEY (number)
);
CREATE TABLE IF NOT EXISTS quran_verse (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    surah_number  SMALLINT  NOT NULL REFERENCES quran_surah (number),
    verse_number  SMALLINT  NOT NULL,          -- ayah within surah
    page          SMALLINT  NOT NULL,          -- 1..604 (Medina Mushaf)
    juz           SMALLINT  NOT NULL,          -- 1..30
    hizb          SMALLINT  NOT NULL,          -- 1..60
    hizb_quarter  SMALLINT  NOT NULL,          -- 1..240 (rub' al-hizb)
    CONSTRAINT pk_quran_verse PRIMARY KEY (id),
    CONSTRAINT uq_quran_verse UNIQUE (surah_number, verse_number)
);
CREATE INDEX idx_quran_verse_page ON quran_verse (page);
CREATE INDEX idx_quran_verse_juz  ON quran_verse (juz);
CREATE INDEX idx_quran_verse_hizb ON quran_verse (hizb);
