--liquibase formatted sql
--changeset houndjo:00014-school-class-create-table
CREATE TABLE IF NOT EXISTS school_class (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id   BIGINT       NOT NULL,
    name              VARCHAR(120) NOT NULL,
    description       TEXT,
    display_order     INT          NOT NULL DEFAULT 0,
    creation_date     TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date  TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_school_class PRIMARY KEY (id),
    CONSTRAINT fk_school_class_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE
);

CREATE INDEX idx_school_class_org ON school_class (organization_id);
