--liquibase formatted sql
--changeset houndjo:00018-enrollment-create-table
CREATE TABLE IF NOT EXISTS enrollment (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id   BIGINT       NOT NULL,
    student_id        BIGINT       NOT NULL,
    class_id          BIGINT       NOT NULL,
    status            VARCHAR(15)  NOT NULL,
    start_date        DATE         NOT NULL,
    end_date          DATE,
    creation_date     TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date  TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_enrollment PRIMARY KEY (id),
    CONSTRAINT fk_enrollment_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE,
    CONSTRAINT fk_enrollment_class FOREIGN KEY (class_id) REFERENCES school_class (id) ON DELETE CASCADE,
    CONSTRAINT fk_enrollment_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE
);

CREATE INDEX idx_enrollment_org ON enrollment (organization_id);
CREATE INDEX idx_enrollment_student ON enrollment (student_id);
CREATE INDEX idx_enrollment_class ON enrollment (class_id);

-- A student can have at most one ACTIVE enrollment in a given class at a time.
CREATE UNIQUE INDEX uq_enrollment_active ON enrollment (student_id, class_id) WHERE status = 'ACTIVE';
