--liquibase formatted sql
--changeset houndjo:00024-attendance-permission-create-table
CREATE TABLE IF NOT EXISTS attendance_permission (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id   BIGINT       NOT NULL,
    student_id        BIGINT       NOT NULL,
    from_date         DATE         NOT NULL,
    to_date           DATE         NOT NULL,
    reason            VARCHAR(255),
    status            VARCHAR(15)  NOT NULL,
    creation_date     TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date  TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_attendance_permission PRIMARY KEY (id),
    CONSTRAINT fk_attendance_permission_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_permission_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE
);

CREATE INDEX idx_attendance_permission_student ON attendance_permission (student_id);
CREATE INDEX idx_attendance_permission_org ON attendance_permission (organization_id);
