--liquibase formatted sql
--changeset houndjo:00023-attendance-create-table
CREATE TABLE IF NOT EXISTS attendance (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id   BIGINT       NOT NULL,
    student_id        BIGINT       NOT NULL,
    session_id        BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    reason            VARCHAR(255),
    creation_date     TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date  TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_attendance PRIMARY KEY (id),
    CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_session FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE,
    CONSTRAINT uq_attendance UNIQUE (student_id, session_id)
);

CREATE INDEX idx_attendance_session ON attendance (session_id);
CREATE INDEX idx_attendance_org ON attendance (organization_id);
