--liquibase formatted sql
--changeset houndjo:00025-fee-schedule-create-table
CREATE TABLE IF NOT EXISTS fee_schedule (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    organization_id   BIGINT        NOT NULL,
    type              VARCHAR(20)   NOT NULL,
    amount            NUMERIC(12,2) NOT NULL,
    currency_code     VARCHAR(10)   NOT NULL,
    label             VARCHAR(150)  NOT NULL,
    active            BOOLEAN       NOT NULL DEFAULT TRUE,
    creation_date     TIMESTAMP     NOT NULL DEFAULT now(),
    last_update_date  TIMESTAMP     NOT NULL DEFAULT now(),
    last_updated_by   VARCHAR(255)  NOT NULL DEFAULT 'system',
    CONSTRAINT pk_fee_schedule PRIMARY KEY (id),
    CONSTRAINT fk_fee_schedule_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE
);

CREATE INDEX idx_fee_schedule_org ON fee_schedule (organization_id);
