--liquibase formatted sql
--changeset houndjo:00022-progress-record-create-table
CREATE TABLE IF NOT EXISTS progress_record (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id   BIGINT       NOT NULL,
    student_id        BIGINT       NOT NULL,
    course_id         BIGINT       NOT NULL,
    session_id        BIGINT       NOT NULL,
    flow              VARCHAR(15)  NOT NULL,
    from_surah        SMALLINT,
    from_verse        SMALLINT,
    to_surah          SMALLINT,
    to_verse          SMALLINT,
    lesson_id         BIGINT,
    chapter_no        SMALLINT,
    page_no           SMALLINT,
    error_count       INT          NOT NULL DEFAULT 0,
    fluency           VARCHAR(15),
    tajweed           VARCHAR(15),
    status            VARCHAR(15)  NOT NULL,
    note              TEXT,
    creation_date     TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date  TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_progress_record PRIMARY KEY (id),
    CONSTRAINT fk_progress_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_course FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_session FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE
);

CREATE INDEX idx_progress_student_course ON progress_record (student_id, course_id);
CREATE INDEX idx_progress_flow ON progress_record (flow);
CREATE INDEX idx_progress_session ON progress_record (session_id);
CREATE INDEX idx_progress_org ON progress_record (organization_id);
