--liquibase formatted sql
--changeset houndjo:00021-session-create-table
CREATE TABLE IF NOT EXISTS session (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id   BIGINT       NOT NULL,
    course_id         BIGINT       NOT NULL,
    teacher_user_id   BIGINT       NULL,
    session_date      DATE         NOT NULL,
    start_time        TIME,
    end_time          TIME,
    status            VARCHAR(15)  NOT NULL,
    creation_date     TIMESTAMP    NOT NULL DEFAULT now(),
    last_update_date  TIMESTAMP    NOT NULL DEFAULT now(),
    last_updated_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    CONSTRAINT pk_session PRIMARY KEY (id),
    CONSTRAINT fk_session_course FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE,
    CONSTRAINT fk_session_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE,
    CONSTRAINT fk_session_teacher FOREIGN KEY (teacher_user_id) REFERENCES app_user (id) ON DELETE SET NULL
);

CREATE INDEX idx_session_course_date ON session (course_id, session_date);
CREATE INDEX idx_session_org ON session (organization_id);
