--liquibase formatted sql
--changeset houndjo:00020-course-pace-create-table
CREATE TABLE IF NOT EXISTS course_pace (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    organization_id     BIGINT        NOT NULL,
    course_id           BIGINT        NOT NULL,
    unit                VARCHAR(15)   NOT NULL,
    amount_per_session  NUMERIC(6,2)  NOT NULL,
    sessions_per_week   INT           NOT NULL,
    sabak_unit          VARCHAR(15),
    sabak_amount        NUMERIC(6,2),
    sabqi_unit          VARCHAR(15),
    sabqi_amount        NUMERIC(6,2),
    dhor_unit           VARCHAR(15),
    dhor_amount         NUMERIC(6,2),
    dhor_cycle_days     INT,
    creation_date       TIMESTAMP     NOT NULL DEFAULT now(),
    last_update_date    TIMESTAMP     NOT NULL DEFAULT now(),
    last_updated_by     VARCHAR(255)  NOT NULL DEFAULT 'system',
    CONSTRAINT pk_course_pace PRIMARY KEY (id),
    CONSTRAINT fk_course_pace_course FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_pace_org FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE,
    CONSTRAINT uq_course_pace_course UNIQUE (course_id)
);

CREATE INDEX idx_course_pace_org ON course_pace (organization_id);
