package com.houndjo.integration.tenancy;

import com.houndjo.application.tenant.TenantContext;
import jakarta.annotation.PostConstruct;
import java.util.List;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Test-only fixture proving the {@link TenantContext} guard end-to-end over a real business
 * record, ahead of the first real tenant-scoped aggregate (E1-1). Not part of production code:
 * lives in {@code houndjo-tests} only, and its backing table is created on the fly rather than
 * through a Liquibase migration.
 */
@RestController
@RequestMapping("/api/test/tenant-fixture")
public class TenantFixtureController {

    private final TenantContext tenantContext;
    private final JdbcTemplate jdbcTemplate;

    public TenantFixtureController(TenantContext tenantContext, JdbcTemplate jdbcTemplate) {
        this.tenantContext = tenantContext;
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    void createFixtureTable() {
        jdbcTemplate.execute(
                """
                CREATE TABLE IF NOT EXISTS tenant_fixture_test (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    organization_id BIGINT NOT NULL,
                    name VARCHAR(255) NOT NULL
                )
                """);
    }

    @GetMapping
    public List<TenantFixtureRecord> list() {
        Long organizationId = tenantContext.requireCurrentOrganizationId();
        return jdbcTemplate.query(
                "SELECT id, name FROM tenant_fixture_test WHERE organization_id = ? ORDER BY id",
                (rs, rowNum) -> new TenantFixtureRecord(rs.getLong("id"), rs.getString("name")),
                organizationId);
    }

    public record TenantFixtureRecord(Long id, String name) {}
}
