--liquibase formatted sql
--changeset houndjo:00006-insert-quran-surahs

INSERT INTO quran_surah (number, name_arabic, name_transliteration, name_fr, name_en, revelation_place, verse_count)
VALUES
    (1, 'الفاتحة', 'Al-Fatihah', 'L''ouverture', 'The Opener', 'MECCAN', 7),
    (2, 'البقرة', 'Al-Baqarah', 'La vache', 'The Cow', 'MEDINAN', 286),
    (3, 'آل عمران', 'Ali ''Imran', 'La famille de ''imran', 'Family of Imran', 'MEDINAN', 200),
    (4, 'النساء', 'An-Nisa', 'Les femmes', 'The Women', 'MEDINAN', 176),
    (5, 'المائدة', 'Al-Ma''idah', 'La table servie', 'The Table Spread', 'MEDINAN', 120),
    (6, 'الأنعام', 'Al-An''am', 'Les bestiaux', 'The Cattle', 'MECCAN', 165),
    (7, 'الأعراف', 'Al-A''raf', 'Al-A''raf', 'The Heights', 'MECCAN', 206),
    (8, 'الأنفال', 'Al-Anfal', 'Le butin', 'The Spoils of War', 'MEDINAN', 75),
    (9, 'التوبة', 'At-Tawbah', 'Le repentir', 'The Repentance', 'MEDINAN', 129),
    (10, 'يونس', 'Yunus', 'Jonas', 'Jonah', 'MECCAN', 109),
    (11, 'هود', 'Hud', 'Houd', 'Hud', 'MECCAN', 123),
    (12, 'يوسف', 'Yusuf', 'Joseph', 'Joseph', 'MECCAN', 111),
    (13, 'الرعد', 'Ar-Ra''d', 'Le tonnerre', 'The Thunder', 'MEDINAN', 43),
    (14, 'ابراهيم', 'Ibrahim', 'Abraham', 'Abraham', 'MECCAN', 52),
    (15, 'الحجر', 'Al-Hijr', 'Al-Hijr', 'The Rocky Tract', 'MECCAN', 99),
    (16, 'النحل', 'An-Nahl', 'Les abeilles', 'The Bee', 'MECCAN', 128),
    (17, 'الإسراء', 'Al-Isra', 'Le voyage nocturne', 'The Night Journey', 'MECCAN', 111),
    (18, 'الكهف', 'Al-Kahf', 'La caverne', 'The Cave', 'MECCAN', 110),
    (19, 'مريم', 'Maryam', 'Marie', 'Mary', 'MECCAN', 98),
    (20, 'طه', 'Taha', 'Ta-Ha', 'Ta-Ha', 'MECCAN', 135),
    (21, 'الأنبياء', 'Al-Anbya', 'Les prophètes', 'The Prophets', 'MECCAN', 112),
    (22, 'الحج', 'Al-Hajj', 'Le pèlerinage', 'The Pilgrimage', 'MEDINAN', 78),
    (23, 'المؤمنون', 'Al-Mu''minun', 'Les croyants', 'The Believers', 'MECCAN', 118),
    (24, 'النور', 'An-Nur', 'La lumière', 'The Light', 'MEDINAN', 64),
    (25, 'الفرقان', 'Al-Furqan', 'Le discernement', 'The Criterion', 'MECCAN', 77),
    (26, 'الشعراء', 'Ash-Shu''ara', 'Les poètes', 'The Poets', 'MECCAN', 227),
    (27, 'النمل', 'An-Naml', 'Les fourmis', 'The Ant', 'MECCAN', 93),
    (28, 'القصص', 'Al-Qasas', 'Le récit', 'The Stories', 'MECCAN', 88),
    (29, 'العنكبوت', 'Al-''Ankabut', 'L''araignée', 'The Spider', 'MECCAN', 69),
    (30, 'الروم', 'Ar-Rum', 'Les romains', 'The Romans', 'MECCAN', 60),
    (31, 'لقمان', 'Luqman', 'Louqman', 'Luqman', 'MECCAN', 34),
    (32, 'السجدة', 'As-Sajdah', 'La prosternation', 'The Prostration', 'MECCAN', 30),
    (33, 'الأحزاب', 'Al-Ahzab', 'Les coalisés', 'The Combined Forces', 'MEDINAN', 73),
    (34, 'سبإ', 'Saba', 'Saba''', 'Sheba', 'MECCAN', 54),
    (35, 'فاطر', 'Fatir', 'Le Créateur', 'Originator', 'MECCAN', 45),
    (36, 'يس', 'Ya-Sin', 'Ya-Sin', 'Ya Sin', 'MECCAN', 83),
    (37, 'الصافات', 'As-Saffat', 'Les rangés', 'Those who set the Ranks', 'MECCAN', 182),
    (38, 'ص', 'Sad', 'Sad', 'The Letter "Saad"', 'MECCAN', 88),
    (39, 'الزمر', 'Az-Zumar', 'Les groupes', 'The Troops', 'MECCAN', 75),
    (40, 'غافر', 'Ghafir', 'Le Pardonneur', 'The Forgiver', 'MECCAN', 85),
    (41, 'فصلت', 'Fussilat', 'Les versets explicites', 'Explained in Detail', 'MECCAN', 54),
    (42, 'الشورى', 'Ash-Shuraa', 'La concertation', 'The Consultation', 'MECCAN', 53),
    (43, 'الزخرف', 'Az-Zukhruf', 'L''ornement', 'The Ornaments of Gold', 'MECCAN', 89),
    (44, 'الدخان', 'Ad-Dukhan', 'La fumée', 'The Smoke', 'MECCAN', 59),
    (45, 'الجاثية', 'Al-Jathiyah', 'L''agenouillée', 'The Crouching', 'MECCAN', 37),
    (46, 'الأحقاف', 'Al-Ahqaf', 'Al-Ahqaf', 'The Wind-Curved Sandhills', 'MECCAN', 35),
    (47, 'محمد', 'Muhammad', 'Mouhammad', 'Muhammad', 'MEDINAN', 38),
    (48, 'الفتح', 'Al-Fath', 'La victoire éclatante', 'The Victory', 'MEDINAN', 29),
    (49, 'الحجرات', 'Al-Hujurat', 'Les appartements', 'The Rooms', 'MEDINAN', 18),
    (50, 'ق', 'Qaf', 'Qaf', 'The Letter "Qaf"', 'MECCAN', 45),
    (51, 'الذاريات', 'Adh-Dhariyat', 'Qui éparpillent', 'The Winnowing Winds', 'MECCAN', 60),
    (52, 'الطور', 'At-Tur', 'Le mont At-Tour', 'The Mount', 'MECCAN', 49),
    (53, 'النجم', 'An-Najm', 'L''étoile', 'The Star', 'MECCAN', 62),
    (54, 'القمر', 'Al-Qamar', 'La lune', 'The Moon', 'MECCAN', 55),
    (55, 'الرحمن', 'Ar-Rahman', 'Le Tout Miséricordieux', 'The Beneficent', 'MEDINAN', 78),
    (56, 'الواقعة', 'Al-Waqi''ah', 'L''inévitable', 'The Inevitable', 'MECCAN', 96),
    (57, 'الحديد', 'Al-Hadid', 'Le fer', 'The Iron', 'MEDINAN', 29),
    (58, 'المجادلة', 'Al-Mujadila', 'La discussion', 'The Pleading Woman', 'MEDINAN', 22),
    (59, 'الحشر', 'Al-Hashr', 'L''exode', 'The Exile', 'MEDINAN', 24),
    (60, 'الممتحنة', 'Al-Mumtahanah', 'L''éprouvée', 'She that is to be examined', 'MEDINAN', 13),
    (61, 'الصف', 'As-Saf', 'Le rang', 'The Ranks', 'MEDINAN', 14),
    (62, 'الجمعة', 'Al-Jumu''ah', 'Le vendredi', 'The Congregation, Friday', 'MEDINAN', 11),
    (63, 'المنافقون', 'Al-Munafiqun', 'Les hypocrites', 'The Hypocrites', 'MEDINAN', 11),
    (64, 'التغابن', 'At-Taghabun', 'La grande perte', 'The Mutual Disillusion', 'MEDINAN', 18),
    (65, 'الطلاق', 'At-Talaq', 'Le divorce', 'The Divorce', 'MEDINAN', 12),
    (66, 'التحريم', 'At-Tahrim', 'L''interdiction', 'The Prohibition', 'MEDINAN', 12),
    (67, 'الملك', 'Al-Mulk', 'La royauté', 'The Sovereignty', 'MECCAN', 30),
    (68, 'القلم', 'Al-Qalam', 'La plume', 'The Pen', 'MECCAN', 52),
    (69, 'الحاقة', 'Al-Haqqah', 'L''inéluctable', 'The Reality', 'MECCAN', 52),
    (70, 'المعارج', 'Al-Ma''arij', 'Les voies d''ascension', 'The Ascending Stairways', 'MECCAN', 44),
    (71, 'نوح', 'Nuh', 'Noé', 'Noah', 'MECCAN', 28),
    (72, 'الجن', 'Al-Jinn', 'Les djinns', 'The Jinn', 'MECCAN', 28),
    (73, 'المزمل', 'Al-Muzzammil', 'L''enveloppé', 'The Enshrouded One', 'MECCAN', 20),
    (74, 'المدثر', 'Al-Muddaththir', 'Celui qui se couvre', 'The Cloaked One', 'MECCAN', 56),
    (75, 'القيامة', 'Al-Qiyamah', 'La résurrection', 'The Resurrection', 'MECCAN', 40),
    (76, 'الانسان', 'Al-Insan', 'L''homme', 'The Man', 'MEDINAN', 31),
    (77, 'المرسلات', 'Al-Mursalat', 'Les envoyés', 'The Emissaries', 'MECCAN', 50),
    (78, 'النبإ', 'An-Naba', 'La nouvelle', 'The Tidings', 'MECCAN', 40),
    (79, 'النازعات', 'An-Nazi''at', 'Ceux qui arrachent', 'Those who drag forth', 'MECCAN', 46),
    (80, 'عبس', '''Abasa', 'Il s''est renfrogné', 'He Frowned', 'MECCAN', 42),
    (81, 'التكوير', 'At-Takwir', 'L''obscurcissement', 'The Overthrowing', 'MECCAN', 29),
    (82, 'الإنفطار', 'Al-Infitar', 'La rupture', 'The Cleaving', 'MECCAN', 19),
    (83, 'المطففين', 'Al-Mutaffifin', 'Les fraudeurs', 'The Defrauding', 'MECCAN', 36),
    (84, 'الإنشقاق', 'Al-Inshiqaq', 'La déchirure', 'The Sundering', 'MECCAN', 25),
    (85, 'البروج', 'Al-Buruj', 'Les constellations', 'The Mansions of the Stars', 'MECCAN', 22),
    (86, 'الطارق', 'At-Tariq', 'L''astre nocturne', 'The Nightcommer', 'MECCAN', 17),
    (87, 'الأعلى', 'Al-A''la', 'Le Très-Haut', 'The Most High', 'MECCAN', 19),
    (88, 'الغاشية', 'Al-Ghashiyah', 'L''enveloppante', 'The Overwhelming', 'MECCAN', 26),
    (89, 'الفجر', 'Al-Fajr', 'L''aube', 'The Dawn', 'MECCAN', 30),
    (90, 'البلد', 'Al-Balad', 'La cité', 'The City', 'MECCAN', 20),
    (91, 'الشمس', 'Ash-Shams', 'Le soleil', 'The Sun', 'MECCAN', 15),
    (92, 'الليل', 'Al-Layl', 'La nuit', 'The Night', 'MECCAN', 21),
    (93, 'الضحى', 'Ad-Duhaa', 'Le jour montant', 'The Morning Hours', 'MECCAN', 11),
    (94, 'الشرح', 'Ash-Sharh', 'L''ouverture', 'The Relief', 'MECCAN', 8),
    (95, 'التين', 'At-Tin', 'Les figues', 'The Fig', 'MECCAN', 8),
    (96, 'العلق', 'Al-''Alaq', 'L''adhérence', 'The Clot', 'MECCAN', 19),
    (97, 'القدر', 'Al-Qadr', 'La destinée', 'The Power', 'MECCAN', 5),
    (98, 'البينة', 'Al-Bayyinah', 'La preuve', 'The Clear Proof', 'MEDINAN', 8),
    (99, 'الزلزلة', 'Az-Zalzalah', 'Le séisme', 'The Earthquake', 'MEDINAN', 8),
    (100, 'العاديات', 'Al-''Adiyat', 'Les coursiers', 'The Courser', 'MECCAN', 11),
    (101, 'القارعة', 'Al-Qari''ah', 'Le fracas', 'The Calamity', 'MECCAN', 11),
    (102, 'التكاثر', 'At-Takathur', 'La course aux richesses', 'The Rivalry in world increase', 'MECCAN', 8),
    (103, 'العصر', 'Al-''Asr', 'Le temps', 'The Declining Day', 'MECCAN', 3),
    (104, 'الهمزة', 'Al-Humazah', 'Les calomniateurs', 'The Traducer', 'MECCAN', 9),
    (105, 'الفيل', 'Al-Fil', 'L''éléphant', 'The Elephant', 'MECCAN', 5),
    (106, 'قريش', 'Quraysh', 'Les Quraysh', 'Quraysh', 'MECCAN', 4),
    (107, 'الماعون', 'Al-Ma''un', 'L''entraide', 'The Small kindnesses', 'MECCAN', 7),
    (108, 'الكوثر', 'Al-Kawthar', 'L''abondance', 'The Abundance', 'MECCAN', 3),
    (109, 'الكافرون', 'Al-Kafirun', 'Les mécréants', 'The Disbelievers', 'MECCAN', 6),
    (110, 'النصر', 'An-Nasr', 'Le secours', 'The Divine Support', 'MEDINAN', 3),
    (111, 'المسد', 'Al-Masad', 'Les fibres', 'The Palm Fiber', 'MECCAN', 5),
    (112, 'الإخلاص', 'Al-Ikhlas', 'La sincérité', 'The Sincerity', 'MECCAN', 4),
    (113, 'الفلق', 'Al-Falaq', 'L''aube naissante', 'The Daybreak', 'MECCAN', 5),
    (114, 'الناس', 'An-Nas', 'Les humains', 'Mankind', 'MECCAN', 6);
